import Head from 'next/head';
import Feed from '../Components/Feed/Feed';
import Header from '../Components/Header/Header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>SozialHub</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Feed />
      {/* Header */}
      {/* Feed */}
      {/* Modal */}
    </div>
  );
}
